[phases.setup]
nixPkgs = ['python3', 'pip3']

[phases.install]
cmds = ['pip install -r requirements_minimal.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python app_railway.py'