services:
  - type: web
    name: invoice-reconciliation-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: PORT
        fromService:
          type: web
          name: invoice-reconciliation-backend
          property: port