services:
  - type: web
    name: invoice-reconciliation-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: "/opt/render/project/src"